### PR TITLE
Tox support +  python 3.3 compatibility

### PR DESCRIPTION
**Pull request by ziadsawalha**

### CODE REVIEW

**Comment by ziadsawalha** [comment]
Could you push a new version to pypi?

**Comment by joepie91** [comment]
Sorry for making you wait! The last few weeks have been chaos... I'll have a look at this tomorrow when I'm more awake, I promise :)

**Comment by ziadsawalha** [comment]
Thanks :-)

**Comment by joepie91** [comment]
Could you have a look at the above two points? Other than that, it seems fine :)

**Comment by ziadsawalha** [comment]
I updated the commits. I'm not thrilled with the solution, but I can't find a better way to do it within the time I had to work on it. Let me know what you think...

**Comment by ziadsawalha** [comment]
@joepie91: ping

**Comment by joepie91** [comment]
Heh, sorry, been very busy again. Either way, after some struggling to get Python 2.6 to work on my system - this is apparently a non-trivial task - I've tested your branch and it all seems to work fine. I'm merging this and pushing a new release to PyPi.

Again, sorry for the delays!

**Comment by joepie91** [comment]
Alright, 2.1.0 is now on PyPI.

**Comment by ziadsawalha** [comment]
Great! Thank you.

**Pull request merged**
