### PR TITLE
Make it work with python 3.x

### PR DESCRIPTION
**Pull request by ziadsawalha**
I got errors trying to run pythonwhois in python 3.x. I believe these changes will fix that.

I ran tests successfully in python 3.3 and 2.7.

### CODE REVIEW

**Comment by joepie91** [comment]
Sorry for the delayed response, I've been crazy busy the past two weeks.

I've run tests under Python 2.6 as well, and these succeeded. The only possible drawback of merging this, would be that there'd be no Python 2.5 compatibility (due to the exception syntax) - however, as far as I am aware 2.5 is not really shipped with any non-EOL distributions anymore, so it shouldn't be too much of an issue.

I should point out that while I can test on Python 3, my primary testing still takes place on Python 2(.7), and I can't guarantee that I won't overlook something that might break Python 3 compatibility in the future. I'll do my best, though :)

Sidenote: Your pull request targets the master branch; since GitHub won't let me retarget it, I'll manually merge it into develop instead, and it'll end up in the next release. That release should happen in a few days at most.

**Comment by ziadsawalha** [comment]
Thanks!

Would you accept a pull request to use `tox` for testing multiple versions of python?

**Comment by joepie91** [comment]
Assuming it wouldn't create any additional significant workload for me (which it doesn't seem to, judging from the site), that'd be very welcome :)

**Comment by ziadsawalha** [comment]
@joepie91 - #7 includes tox and a bunch of python 3.3 fixes as a result.

**Pull request closed without merging**
