### PR TITLE
added .de region specific support

### PR DESCRIPTION
**Pull request by ckoepp**
You seem to query whois.denic.de for the .de TLD. Unfortunately no data is received by your module as you're lacking the `-T dn,ace -C US-ASCII` string _before_ the actually domain to query.

You can easily check the behaviour through
`echo "-T dn,ace -C US-ASCII test.de" | nc whois.denic.de 43` and `echo "test.de" | nc whois.denic.de 43`

Added domain `test.de` to test-cases as this very domain is unlikely to change over time due to the state-sponsored organisation behind.

Test-cases are green and I guess there is no need to print the whole output there considered the case that this change is a quite trivial one. I do hope you agree :smile:

### CODE REVIEW

**Comment by joepie91** [comment]
It seems good to go - the requirement of test.py output is primarily to make sure that people _have_ tested it, which seems to be the case here :)

I do have one question before merging, though: is all WHOIS data for the entire `.de` TLD handled by whois.denic.de, or is there a possibility of a redirect to another WHOIS server? If redirects are a possibility, it should probably only apply those flags when querying `whois.denic.de` in particular, and not for everything ending in `.de` (similar to how the language flag is handled for `.jp`).

I also notice that this doesn't yet parse registrant data for whois.denic.de - while this is of course not required for this pull request, I'll make sure to implement that later (unless you were planning on doing so and submitting a pull request, in which case I'll avoid duplication of effort).

**Comment by ckoepp** [comment]
That's a good question actually...

I couldn't find any standard for such unusual behaviour to be honest. But since `de.whois-servers.net` is also pointing to 81.91.170.6 (= `whois.denic.de`) it may be safer to check for those names additionally.

Refererer services like `whois.iana.org` don't accept a request like this:

`echo "-T dn,ace -C US-ASCII test.de" | nc whois.iana.org 43` versus `
  echo "test.de" | nc whois.iana.org 43`

So yes, there should be check for the two domains pointing to the whois DeNIC service. Although there may be more domains pointing to this very IP, but I guess those are quite exotic ones, right? So a simple check should do it.

**Comment by ckoepp** [comment]
...I also added an simple rfc3490 encoding feature (with two tests and documentation).

Have a look - although quite uncommon, some domains of local businesses are using it.

**Comment by joepie91** [comment]
Whoops, sorry for not responding earlier! I've been very busy for the past two weeks...

Could you add the test output after your .de parsing changes? I should also add that if you name the matching groups street1, street2 etc. they will be combined into a single newline-delimited address :)

**Comment by ckoepp** [comment]
No problem about the delay.

You can find an example for the .de parsing in `test/target_default/test.de` or `test/target_normalized/test.de`. I also added the update of two domains as their name-servers changed.

 Maybe you like to do an automated testing with travis-ci and use mocked data for simulating the whois services. By doing so every single pull request will be tested and the result is visible within seconds for everybody. Also no changed in whois-records are to break the tests (like it is the case currently).

To be honest I find it kind of annoying to copy'n'paste the whole bunch of testing output here :smile: 
It's working and can be verified by checking out my fork.

The street-solution is not ideal but resilient. Because I have no idea what the maximum amount of `Address` fields is. The only thing I found is that the street is always the last one of them as those others contain stuff like "c/o Sombody" or just a copy of the `Organisation` field. So I left it like this for now - but one can change that of course and try to get out more information :)

**Comment by joepie91** [comment]
After some more delays, I've finally gotten around to testing your pull request. It caused an error in Python 3.3 (which is supported since a few days ago after #4, and now tested through Tox), but this just turned out to be spaces as whitespace in your code, where the rest of the code uses tabs - so I've gone ahead and fixed that.

I've manually merged your pull request - it was targeted at `master` rather than `develop`, and the new version is now live on PyPI. Thanks for your help :)

**Pull request merged**
